name: Get Processed Variables

on:
  workflow_call: {} # allow this workflow to be called from other workflows

jobs:
  create_processed_variables:
    name: Create Processed Variables
    runs-on: ubuntu-latest
    # Use via one of the following as env or directly in `run`:
    #   ${{ needs.create_processed_variables.outputs.<output_id> }}
    #   ${{ steps.set_processed_variables.outputs.<output_id> }}
    outputs:
      branchName: ${{ steps.set_processed_variables.outputs.branchName }}
      tagName: ${{ steps.set_processed_variables.outputs.tagName }}
      issueNumber: ${{ steps.set_processed_variables.outputs.issueNumber }}
    steps:
      - name: Set Processed Variables
        id: set_processed_variables
        uses: actions/github-script@v7
        with:
          script: |
            // get the branch name (only available when run on branches, commits or tags - not when run on PRs)
            const branchNameRaw = context?.payload?.base_ref
            const branchName = branchNameRaw?.startsWith('refs/heads/') 
              ? branchNameRaw?.replace(/^refs\/heads\//, "") 
              : undefined

            // get the tag name (can be 'refs/tags/<TAG_NAME>', 'refs/pull/<PR_NUMBER>/merge', ...)
            const tagNameRaw = context?.ref ?? context?.payload?.ref
            const tagName = tagNameRaw?.startsWith('refs/tags/') 
              ? tagNameRaw?.replace(/^refs\/tags\//, "") 
              : undefined

            // get the issue/ PR number
            const issueNumber = context?.issue?.number || context?.payload?.pull_request?.number

            // set outputs
            core.setOutput("branchName", branchName)
            core.setOutput("tagName", tagName)
            core.setOutput("issueNumber", issueNumber)
