name: Vercel Production Deployment

on:
  push:
    # This is a OR, not a AND, so we ignore the check for the main branch
    # branches:
    #   - main
    tags:
      - '20[0-9]+-[0-9]+-[0-9]+'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_ZLIG_DEMO_BASE_URL: ${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}

jobs:
  vercel-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: set up pnpm
        run: pnpm setup

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
