name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_ZLIG_DEMO_BASE_URL: ${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}

jobs:
  vercel-deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Setup pnpm as package manager
      #   uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
      #   with:
      #       version: 9.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Configure PNPM Global Directory
        run: |
          pnpm setup
          echo "export PATH=$(pnpm root -g)/../bin:\$PATH" >> $GITHUB_ENV

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
