name: Vercel Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  VERCEL_TELEMETRY_DISABLED: 1
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VITE_ZLIG_DEMO_BASE_URL: ${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}

jobs:
  dependence:
    uses: ./.github/workflows/lint.yml

  vercel-deploy-preview:
    name: Vercel Deploy Preview
    needs: dependence
    runs-on: ubuntu-latest
    outputs: # needs `id` to reference the output
      deploymentUrl: ${{ steps.deploy.outputs.deploymentUrl }}
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v3

      # - name: Enable Corepack
      #   run: corepack enable

      - name: Setup pnpm as package manager
        uses: pnpm/action-setup@v3
        with:
          version: 9.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
          VITE_ZLIG_DEMO_BASE_URL: ${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}
        run: |
          export VITE_ZLIG_DEMO_BASE_URL="${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}"
          echo "VITE_ZLIG_DEMO_BASE_URL=${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}" >> $GITHUB_ENV
          VITE_ZLIG_DEMO_BASE_URL="${{ secrets.VITE_ZLIG_DEMO_BASE_URL }}" vercel build --token=${{ secrets.VERCEL_TOKEN }}
          # vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          # use the PR number as preview url
          vercel deploy --prebuilt --token="${{ secrets.VERCEL_TOKEN }}" --name="pr-${{ github.event.number }}" > deploy.log
          URL=$(cat deploy.log | grep -o 'https:\/\/[^ ]*.vercel.app' | head -n1)
          echo "deploymentUrl=$URL" >> $GITHUB_OUTPUT

      # - name: Vercel Action
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel token
      #     # vercel-args: # Vercel args (optional)
      #     github-comment: true # if you want to comment on pr and commit, set true, default: true (optional)
      #     # github-token: # if you want to comment on pr and commit, set token (optional)
      #     github-deployment: false # if you want to create github deployment, set true, default: false (optional)
      #     # working-directory: # the working directory (optional)
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel project id
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Vercel org id
      #     # vercel-project-name: # The name of the project; if absent, the `vercel inspect` command is used to determine. (optional)
      #     # vercel-version: # vercel-cli package version (optional)
      #     # scope: # If you are work in team scope, you should set this value to your team id. (optional)
      #     # zeit-token: # zeit.co token (optional)
      #     # now-args: # (optional)
      #     # now-project-id: # (optional)
      #     # now-org-id: # (optional)
      #     # alias-domains: # You can assign a domain to this deployment. Please note that this domain must have been configured in the project. You can use pull request number via `{{PR_NUMBER}}` and branch via `{{BRANCH}}` (optional)

  add-comment-to-pr:
    name: Add Comment to PR
    needs: vercel-deploy-preview
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment Preview URL to PR
        uses: actions/github-script@v7
        id: comment-deployment-url-script
        env:
          DEPLOYMENT_URL: ${{ needs.vercel-deploy-preview.outputs.deploymentUrl }}
        with:
          script: |
            // Get pull requests that are open for current ref
            const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })

            // Set issue number for following calls from context (if on pull request event) or from above variable.
            const issueNumber = context.issue.number || context.payload.pull_request.number || pullRequests.data[0].number

            // Set output prefix
            const outputPrefix = "👀 Preview deployed"

            // Get the current date and time
            const now = (new Date).toISOString()

            // Create the output message
            const output = `${outputPrefix}

              | URL | ${process.env.DEPLOYMENT_URL} |
              |:---|:---|
              | Last Updated | ${now} |
            `

            // Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
                ...context.repo,
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
            })

            // Find the bot comment for this workflow
            const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes(outputPrefix)
            })

            // If we have a comment, update it, otherwise create a new one
            if (botComment) {
                github.rest.issues.updateComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: botComment.id,
                    body: output
                })
            } else {
                github.rest.issues.createComment({
                    issue_number: issueNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                })
            }
